### ISSUE TITLE
Wrong s3 policy setup in cloud formation ?

### ISSUE THREAD

**Issue by isp0000** [gilt/s3-sftp-bridge#13]
I'm investigating why all my s3 events (s3 -> sftp) ends up in SQS queue for failed, but files are transferred to sftp correctly. 

There is AccessDenied error generated by code changing s3 object metedata:

`              .then(function(sftpFiles) {
                var metadata = objectData.Metadata || {};
                metadata["synched"] = "true";
                return awsS3.copyObjectAsync({
                  Bucket: record.s3.bucket.name,
                  Key: record.s3.object.key,
                  CopySource: record.s3.bucket.name + "/" + record.s3.object.key,
                  Metadata: metadata,
                  MetadataDirective: 'REPLACE'
                });`
              });
`

AccessDenied: Access Denied
at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/services/s3.js:539:35)
at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:678:14)
at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)
at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)
at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10
at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)
at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:680:12)
at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:678:14)
at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)
at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)
at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10
at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)

**Comment by crystalschang** [comment]
I ran into an "Access Denied" issue as well, but earlier in the function:
https://github.com/gilt/s3-sftp-bridge/blob/master/main.js#L117

I got past this once I updated the bucket policy to allow access from the created bridge role, but now I'm running into a new error after that: `NoSuchKey: The specified key does not exist.`

I don't have any issues when syncing from SFTP -> S3 -- it's just from S3 to SFTP. Any ideas what might be configured incorrectly?

**Comment by rtparungao** [comment]
any update on this? having the same issue right now with S3 to SFTP `NoSuchKey: The specified key does not exist.` 

I'm using NodeJS with Serverless
