### ISSUE TITLE
Trouble creating config file

### ISSUE THREAD

**Issue by damienboley** [gilt/s3-sftp-bridge#19]
I named the config file svs-sftp-to-s3.json
Do I need to update that in the main.js or does it use that name from 

BridgeFunctionName | svs-sftp-to-s3
-- | --

**Comment by AukeTembrink** [comment]
I am not sure because I am trying around with it, too. But I managed to update/create a config file like this:

1. Make sure you have got installed the aws cli on your local machine
2. Create your wanted config file (local)
3. Add the user you are using with your cli to the allowed users of the KMS key
4. Make sure you have the same KMS key selected in your Lambda Management Console for the environment variables
5. Download the following script and make it executable https://github.com/gilt/aws-lambda-config/blob/master/bin/put-config
6. Open your local Terminal/CMD or what ever you use
7. Open the put-config script with the following parameters:
`./put-config -c config -f your-local-config.json -k the-arn-of-your-kms-key -n name-of-your-lambda`

That did the trick for me to upload and create config files for lambda functions.
The idea behind that is the following:
Environment variables in AWS Lambda do not allow "," separated content. So what you are going to do is simply encrypt the content of the config file with your KMS Key to get a encrypted string of the config. This string is placed as a environment variable with the name "config". The Lambda function itself is now able to decrypt the string with the given kms key. On that way you are providing a comma using config file within AWS Lambda.

**Comment by damienboley** [comment]
The message I continue to see is
2018-05-08T15:54:38.773Z	1c698116-52d8-11e8-9493-e38c7b5a08bd
{
    "errorMessage": "Required config not found in environment variable [CONFIG]",
    "errorType": "Error",
    "stackTrace": [
        "getConfig (/var/task/node_modules/aws-lambda-config/index.js:27:16)",
        "Object.kms.decrypt.exports.getConfig (/var/task/node_modules/aws-lambda-config/index.js:37:10)",
        "Object.tryCatcher (/var/task/node_modules/bluebird/js/release/util.js:16:23)",
        "Object.ret [as getConfigAsync] (eval at <anonymous> (/var/task/node_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:13:39)",
        "/var/task/main.js:32:17",
        "tryCatcher (/var/task/node_modules/bluebird/js/release/util.js:16:23)",
        "Function.Promise.attempt.Promise.try (/var/task/node_modules/bluebird/js/release/method.js:39:29)",
        "Object.exports.pollSftp (/var/task/main.js:20:21)",
        "exports.handle (/var/task/main.js:15:20)"
    ]
}

**Comment by damienboley** [comment]
@AukeTembrink I replaced the main.js created with the cloud watch template with what you have in gitHub since they didn't seem to match.  Here is the error I see now
Unable to import module 'main': Error
at Function.Module._resolveFilename (module.js:325:15)
at Function.Module._load (module.js:276:25)
at Module.require (module.js:353:17)
at require (internal/module.js:12:17)
at Object.<anonymous> (/var/task/main.js:3:33)
at Module._compile (module.js:409:26)
at Object.Module._extensions..js (module.js:416:10)
at Module.load (module.js:343:32)
at Function.Module._load (module.js:300:12)
at Module.require (module.js:353:17)
at require (internal/module.js:12:17)

**Comment by damienboley** [comment]
@AukeTembrink built it again using the cloud formation template and got this error again
2018-05-08T18:12:52.813Z	f8c4016e-52ea-11e8-8e49-b99fd5c68af6	UnknownException: Error: Required config not found in environment variable [CONFIG]
at getConfig (/var/task/node_modules/aws-lambda-config/index.js:27:16)
at Object.kms.decrypt.exports.getConfig (/var/task/node_modules/aws-lambda-config/index.js:37:10)
at Object.tryCatcher (/var/task/node_modules/bluebird/js/release/util.js:16:23)
at Object.ret [as getConfigAsync] (eval at <anonymous> (/var/task/node_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:13:39)
at /var/task/main.js:32:17
at tryCatcher (/var/task/node_modules/bluebird/js/release/util.js:16:23)
at Function.Promise.attempt.Promise.try (/var/task/node_modules/bluebird/js/release/method.js:39:29)
at Object.exports.pollSftp (/var/task/main.js:20:21)
at exports.handle (/var/task/main.js:15:20)

**Comment by LanceKonradi-AB** [comment]
Add environment variable in the function page. Name: CONFIG ; Value: URL to s3 location of config file

**Comment by iriekun** [comment]
> @damienboley I am not sure because I am trying around with it, too. But I managed to update/create a config file like this:
> 
> 1. Make sure you have got installed the aws cli on your local machine
> 2. Create your wanted config file (local)
> 3. Add the user you are using with your cli to the allowed users of the KMS key
> 4. Make sure you have the same KMS key selected in your Lambda Management Console for the environment variables
> 5. Download the following script and make it executable https://github.com/gilt/aws-lambda-config/blob/master/bin/put-config
> 6. Open your local Terminal/CMD or what ever you use
> 7. Open the put-config script with the following parameters:
>    `./put-config -c config -f your-local-config.json -k the-arn-of-your-kms-key -n name-of-your-lambda`
> 
> That did the trick for me to upload and create config files for lambda functions.
> 
> The idea behind that is the following:
> Environment variables in AWS Lambda do not allow "," separated content. So what you are going to do is simply encrypt the content of the config file with your KMS Key to get a encrypted string of the config. This string is placed as a environment variable with the name "config". The Lambda function itself is now able to decrypt the string with the given kms key. On that way you are providing a comma using config file within AWS Lambda.

@AukeTembrink I got this error when running put-config script 

``Error parsing parameter '--environment': Expected: ',', received: 'EOF' for input:
Variables={config=}``
